package com.example.inventory.data

import androidx.room.Entity
import androidx.room.PrimaryKey


/**
 * [Item] entity data class creates the database table "items"
 * and then represents a single row (item) in the database.
 * An entity is a single row in a table.
 *
 * "items" is the name of the SQLite table being created.
 * [id] is the autogenerated unique primary key for each (item) row inserted in the table.
 * [name] is the name of the newly added inventory item.
 * [price] is the inventory item's price.
 * [quantity] id the quantity available of the added inventory item.
 */
@Entity(tableName = "items")
data class Item(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val name: String,
    val price: Double,
    val quantity: Int
)
